output_file: README.md
max_items: 5
activity_types:
  - PushEvent
  - PullRequestEvent
  - IssuesEvent
  - IssueCommentEvent
  - PullRequestReviewCommentEvent
  - WatchEvent
comment_start: "<!--START_SECTION:activity-->"
comment_end: "<!--END_SECTION:activity-->"

