name: Recent Activity

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:     # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate recent activity
        uses: Readme-Workflows/recent-activity@v2.3.0
        with:
          GH_USERNAME: fqthedeveloper
          CONFIG_FILE: ./.github/recent-activity.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "chore: update recent activity"
          git push
